INSERT INTO CUSTOMER_ORDER (CUSTOMER, ASSET, SIDE, SIZE, PRICE, STATUS, CREATE_DATE) VALUES (111,'ASSET1','BUY',1,1, 'PENDING', CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER_ORDER (CUSTOMER, ASSET, SIDE, SIZE, PRICE, STATUS, CREATE_DATE) VALUES (222,'ASSET2','BUY',2,2, 'PENDING', CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER_ORDER (CUSTOMER, ASSET, SIDE, SIZE, PRICE, STATUS, CREATE_DATE) VALUES (333,'ASSET3','SELL',3,3, 'PENDING', CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER_ORDER (CUSTOMER, ASSET, SIDE, SIZE, PRICE, STATUS, CREATE_DATE) VALUES (444,'ASSET4','SELL',4,4, 'PENDING', CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER_ORDER (CUSTOMER, ASSET, SIDE, SIZE, PRICE, STATUS, CREATE_DATE) VALUES (555,'ASSET5','SELL',5,5, 'PENDING', CURRENT_TIMESTAMP());

INSERT INTO ASSET(CUSTOMER,ASSET_NAME,SIZE,USABLE_SIZE) VALUES (111,'TRY',1000000,10000);