DROP TABLE IF EXISTS CUSTOMER_ORDER;
CREATE TABLE CUSTOMER_ORDER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER INT,
    ASSET VARCHAR(48),
    SIDE VARCHAR(4),
    SIZE INT,
    PRICE INT,
    STATUS VARCHAR2(8),
    CREATE_DATE DATE
);

ALTER TABLE CUSTOMER_ORDER ADD CONSTRAINT C_CUSTOMERORDER_SIDE_CHK CHECK SIDE IN ('BUY', 'SELL');
ALTER TABLE CUSTOMER_ORDER ADD CONSTRAINT C_CUSTOMERORDER_STATUS_CHK CHECK STATUS IN ('PENDING', 'MATCHED', 'CANCELED');

DROP TABLE IF EXISTS ASSET;
CREATE TABLE ASSET(
    id INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER INT,
    ASSET_NAME VARCHAR2(48),
    SIZE INT,
    USABLE_SIZE INT
);

